# Generated by Django 4.2.20 on 2025-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='donationrequests',
            options={'verbose_name': 'Donation Request', 'verbose_name_plural': 'Donation Requests'},
        ),
        migrations.AlterField(
            model_name='donationrequests',
            name='upload_medical_doc',
            field=models.FileField(upload_to='medical_docs/'),
        ),
    ]
