[build]
  command = "pip install --upgrade pip setuptools && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
  publish = "static"  # Or the appropriate directory where your static files are generated

[build.environment]
  # Specify the Python version to use
  PYTHON_VERSION = "3.8.10"