[build]
  command = "pip install --upgrade pip setuptools && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
  publish = "staticfiles"  # This should be the directory where static files are collected after running collectstatic

[build.environment]
  # Specify the Python version to use
  PYTHON_VERSION = "3.8.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true