[build]
  # Custom build command
  command = "pip install --upgrade pip setuptools && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic"
  publish = "build"